In [5]:
pip install pandas

Requirement already satisfied: pandas in c:\users\akash s\appdata\local\programs\python\python313\lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\akash s\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\akash s\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\akash s\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\akash s\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
# loading dataset using pandas
import pandas as pd

df = pd.read_csv('ecommerce_10000.csv')

In [7]:
df.head(10)

,OrderID,Product,Category,Brand,Platform,City,Price,Quantity,TotalAmount,Rating,Reviews,OrderDate
0,ORD100000,Samsung Galaxy A14,Electronics,Samsung,Souq,Cairo,16284.02,1,16284.02,1.39,1684,11-11-2024
1,ORD100001,Nike Air Max,Fashion,Nike,Jumia,Alexandria,6645.20,2,13290.40,2.56,3604,22-06-2024
2,ORD100002,Bluetooth Headset,Accessories,JBL,Jumia,Casablanca,8882.92,3,26648.76,4.98,1257,27-05-2024
3,ORD100003,HP Pavilion Laptop,Computers,HP,Souq,Dubai,3665.44,1,3665.44,1.44,662,25-07-2024
4,ORD100004,iPhone 13,Electronics,Apple,Souq,Casablanca,5210.37,2,10420.74,3.73,2424,19-02-2024
5,ORD100005,T-shirt Cotton,Fashion,Generic,Souq,Riyadh,19869.86,5,99349.30,3.91,2154,28-09-2024
6,ORD100006,T-shirt Cotton,Fashion,Generic,Souq,Casablanca,17796.11,2,35592.22,4.18,4309,02-07-2024
7,ORD100007,Smartwatch FitPro,Wearables,FitPro,Souq,Casablanca,13081.14,3,39243.42,2.98,3504,30-01-2024
8,ORD100008,T-shirt Cotton,Fashion,Generic,Amazon,Dubai,510.30,5,2551.50,1.17,178,21-09-2024
9,ORD100009,Xiaomi Redmi Note 12,Electronics,Xiaomi,Jumia,Riyadh,6326.57,3,18979.71,2.05,4589,26-09-2024

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   OrderID      10000 non-null  str
 1   Product      10000 non-null  str
 2   Category     10000 non-null  str
 3   Brand        10000 non-null  str
 4   Platform     10000 non-null  str
 5   City         10000 non-null  str
 6   Price        10000 non-null  float64
 7   Quantity     10000 non-null  int64
 8   TotalAmount  10000 non-null  float64
 9   Rating       10000 non-null  float64
 10  Reviews      10000 non-null  int64
 11  OrderDate    10000 non-null  str
dtypes: float64(3), int64(2), str(7)
memory usage: 937.6 KB

In [9]:
# Summary of Statistics using .describe()
df.describe(include='all')

,OrderID,Product,Category,Brand,Platform,City,Price,Quantity,TotalAmount,Rating,Reviews,OrderDate
count,10000,10000,10000,10000,10000,10000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000
unique,10000,10,5,10,3,6,NaN,NaN,NaN,NaN,NaN,361
top,ORD100000,Samsung Galaxy A14,Electronics,Samsung,Souq,Cairo,NaN,NaN,NaN,NaN,NaN,02-12-2024
freq,1,1043,3028,1043,3371,1705,NaN,NaN,NaN,NaN,NaN,46
mean,NaN,NaN,NaN,NaN,NaN,NaN,10027.986331,3.006200,30199.572439,3.005592,2520.072200,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,5728.261196,1.415472,23861.789828,1.154845,1443.849734,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,105.590000,1.000000,113.550000,1.000000,0.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,4999.862500,2.000000,11066.910000,2.010000,1275.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,10063.600000,3.000000,23671.630000,3.005000,2537.500000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,14938.430000,4.000000,44648.580000,4.000000,3767.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,19999.340000,5.000000,99993.800000,5.000000,5000.000000,NaN

In [10]:
# Checking if missing data or null data present in the dataset
df.isnull().sum()

OrderID        0
Product        0
Category       0
Brand          0
Platform       0
City           0
Price          0
Quantity       0
TotalAmount    0
Rating         0
Reviews        0
OrderDate      0
dtype: int64

In [11]:
df.columns

Index(['OrderID', 'Product', 'Category', 'Brand', 'Platform', 'City', 'Price',
       'Quantity', 'TotalAmount', 'Rating', 'Reviews', 'OrderDate'],
      dtype='str')

In [12]:
df.columns = df.columns.str.lower()

In [13]:
df.columns

Index(['orderid', 'product', 'category', 'brand', 'platform', 'city', 'price',
       'quantity', 'totalamount', 'rating', 'reviews', 'orderdate'],
      dtype='str')

In [ ]:
# Correcting Data columns from str (dtype) to datatime using pandas
df["orderdate"] = pd.to_datetime(df["orderdate"], format='%d-%m-%Y')

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   orderid      10000 non-null  str
 1   product      10000 non-null  str
 2   category     10000 non-null  str
 3   brand        10000 non-null  str
 4   platform     10000 non-null  str
 5   city         10000 non-null  str
 6   price        10000 non-null  float64
 7   quantity     10000 non-null  int64
 8   totalamount  10000 non-null  float64
 9   rating       10000 non-null  float64
 10  reviews      10000 non-null  int64
 11  orderdate    10000 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(3), int64(2), str(6)
memory usage: 937.6 KB

In [ ]:
# checking brand consistency whether having like 'Apple', 'apple'
df['brand'].unique()

<StringArray>
['Samsung',    'Nike',     'JBL',      'HP',   'Apple', 'Generic',  'FitPro',
  'Xiaomi',    'Dell',  'Adidas']
Length: 10, dtype: str

In [ ]:
# Checking impossible values
df[df['rating'] > 5 ]

Empty DataFrame
Columns: [orderid, product, category, brand, platform, city, price, quantity, totalamount, rating, reviews, orderdate]
Index: []

In [41]:
# Creating Month and Year for insights
df["month"] = df["orderdate"].dt.month
df["year"] = df["orderdate"].dt.year
df["day_name"] = df["orderdate"].dt.day_name()

In [47]:
df = df.rename(columns={'totalamount':'total_amount'})
df = df.rename(columns={'orderdate':'order_date'})

In [48]:
df.head(3)

,orderid,product,category,brand,platform,city,price,quantity,total_amount,rating,reviews,order_date,month,year,day_name
0,ORD100000,Samsung Galaxy A14,Electronics,Samsung,Souq,Cairo,16284.02,1,16284.02,1.39,1684,2024-11-11,11,2024,Monday
1,ORD100001,Nike Air Max,Fashion,Nike,Jumia,Alexandria,6645.20,2,13290.40,2.56,3604,2024-06-22,6,2024,Saturday
2,ORD100002,Bluetooth Headset,Accessories,JBL,Jumia,Casablanca,8882.92,3,26648.76,4.98,1257,2024-05-27,5,2024,Monday

In [50]:
df.to_csv("cleaned_ecommerce.csv", index=False)

In [14]:
pip install pymysql sqlalchemy

Requirement already satisfied: pymysql in c:\users\akash s\appdata\local\programs\python\python313\lib\site-packages (1.1.3)
Requirement already satisfied: sqlalchemy in c:\users\akash s\appdata\local\programs\python\python313\lib\site-packages (2.0.49)
Requirement already satisfied: greenlet>=1 in c:\users\akash s\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (3.5.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\akash s\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [49]:
from sqlalchemy import create_engine

# MySQL connection
username = "root"
password = "akash123"
host = "localhost"
port = "3307"
database = "ecommerce_db"


engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

# Write DataFrame to MySQL
table_name = "ecommerce"
df.to_sql(table_name, engine, if_exists="replace", index=False)

# Read back sample
pd.read_sql("SELECT * FROM ecommerce LIMIT 5;", engine)

,orderid,product,category,brand,platform,city,price,quantity,total_amount,rating,reviews,order_date,month,year,day_name
0,ORD100000,Samsung Galaxy A14,Electronics,Samsung,Souq,Cairo,16284.02,1,16284.02,1.39,1684,2024-11-11,11,2024,Monday
1,ORD100001,Nike Air Max,Fashion,Nike,Jumia,Alexandria,6645.20,2,13290.40,2.56,3604,2024-06-22,6,2024,Saturday
2,ORD100002,Bluetooth Headset,Accessories,JBL,Jumia,Casablanca,8882.92,3,26648.76,4.98,1257,2024-05-27,5,2024,Monday
3,ORD100003,HP Pavilion Laptop,Computers,HP,Souq,Dubai,3665.44,1,3665.44,1.44,662,2024-07-25,7,2024,Thursday
4,ORD100004,iPhone 13,Electronics,Apple,Souq,Casablanca,5210.37,2,10420.74,3.73,2424,2024-02-19,2,2024,Monday